version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "pr-deps"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    labels:
      - "pr-deps"
  - package-ecosystem: "gomod"
    directory: "/x"
    schedule:
      interval: "weekly"
    labels:
      - "pr-deps"
      