# This workflow runs benchmarks against the current branch, compares them to benchmarks against
# master, and uploads the results as an artifact.

# TODO: This workflow could be improved by only running on pull requests and then posting the results back
# as a comment in the pull request.

name: Benchstat

on: [push, pull_request]

jobs:
  incoming:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:637
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Benchmark
        run: |
          for i in {1..5}; do
            go test -run=^$ -bench=. ./... | tee -a bench.txt
          done
      - name: Upload Benchmark
        uses: actions/upload-artifact@v2
        with:
          name: bench-incoming
          path: bench.txt
  current:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:637
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Benchmark
        run: |
          for i in {1..5}; do
            go test -run=^$ -bench=. ./... | tee -a bench.txt
          done
      - name: Upload Benchmark
        uses: actions/upload-artifact@v2
        with:
          name: bench-current
          path: bench.txt
  benchstat:
    needs: [incoming, current]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install benchstat
        run: go get -u golang.org/x/perf/cmd/benchstat
      - name: Download Incoming
        uses: actions/download-artifact@v2
        with:
          name: bench-incoming
      - name: Download Current
        uses: actions/download-artifact@v2
        with:
          name: bench-current
      - name: Benchstat Results
        run: benchstat bench-current/bench.txt bench-incoming/bench.txt | tee -a benchstat.txt
      - name: Upload benchstat results
        uses: actions/upload-artifact@v2
        with:
          name: benchstat
          path: benchstat.txt
