name: Go

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.14.x, 1.15.x]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.txt

      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.txt

      - name: Benchmark Test
        run: go test -run=^$ -bench=. ./... | tee -a bench.txt

      - name: Upload Benchmark
        uses: actions/upload-artifact@v2
        with:
          name: bench-${{ matrix.os }}-${{ matrix.go-version }}
          path: bench.txt
